# Generated by Django 4.0.3 on 2022-03-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('branch', models.CharField(choices=[('MH', 'MH'), ('CL', 'CL'), ('CH', 'CH'), ('IC', 'IC'), ('IT', 'IT'), ('CE', 'CE'), ('EC', 'EC'), ('FOD', 'FOD'), ('FOP', 'FOP')], max_length=3)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
