# Generated by Django 4.0.3 on 2022-03-12 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import classes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0002_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', classes.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', classes.CharField(max_length=50)),
                ('description', classes.TextField()),
                ('author', classes.CharField(max_length=20)),
                ('publishers', classes.CharField(max_length=50)),
                ('available_qty', classes.IntegerField(default=1)),
                ('book_pic', classes.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', classes.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', classes.DateField(auto_now_add=True)),
                ('due_date', classes.DateField(default=classes.models.one_month)),
                ('current_status', classes.CharField(choices=[('iss', 'issued'), ('ret', 'returned'), ('ren', 'renewed')], max_length=8)),
                ('book_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.book')),
                ('user_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', classes.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', classes.DateField(auto_now_add=True)),
                ('book_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.book')),
                ('user_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', classes.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', classes.TextField()),
                ('book_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.book')),
                ('user_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', classes.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', classes.IntegerField()),
                ('entry_date', classes.DateField(auto_now_add=True)),
                ('due_date', classes.DateField(default=classes.models.one_month)),
                ('book_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.book')),
                ('user_id', classes.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
