# Generated by Django 4.0.3 on 2022-03-12 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
