# Generated by Django 4.0.3 on 2022-03-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_requests_request_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(default='1'),
        ),
    ]
