# Generated by Django 4.0.3 on 2022-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_requests_request_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
