# Generated by Django 4.0.3 on 2022-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_profile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
