# Generated by Django 4.0.3 on 2022-04-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_profile_semester'),
        # ('tables', '0004_rename_sem_profile_semester'),
    ]

    operations = [
    ]
