# Generated by Django 4.0.3 on 2022-04-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_merge_20220402_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_status',
            field=models.CharField(choices=[('issued', 'issued'), ('returned', 'returned'), ('renewed', 'renewed')], max_length=8),
        ),
    ]
