# Generated by Django 4.0.3 on 2022-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_transaction_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Mathematics', 'Mathematics'), ('Language', 'Language'), ('Business Management', 'Business Management'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Robotics', 'Robotics'), ('Space and Astronomy', 'Space and Astronomy')], default='Technology', max_length=25),
        ),
        migrations.AddField(
            model_name='request',
            name='admin_status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='user_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(default='1'),
        ),
    ]
