# Generated by Django 4.0.3 on 2022-04-04 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_book_category_request_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
